version: '3.8'

services:
  app:
    build: .
    container_name: react-vite-app
    ports:
      - "8080:80"  # Redirige el puerto 8080 de tu máquina al puerto 80 del contenedor
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - "8080:80"

volumes:
  db_data:
